In [1]:
import numpy as np
import array

In [2]:
l = [1,2,3,4,5,6,7,8,9,10]
np.array(l)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
type(np.array(l))

numpy.ndarray

In [4]:
np.array([1,2,3,4,5,"ukc",4+5j])

array(['1', '2', '3', '4', '5', 'ukc', '(4+5j)'], dtype='<U64')

In [5]:
np.array([1,2,3,4,5,6.0])

array([1., 2., 3., 4., 5., 6.])

In [6]:
# same shape

np.array([1,3],[2,5],[9,7])

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [7]:
# same shape -----> ARRAY

np.array([[1,3],[2,5],[9,7]])

array([[1, 3],
       [2, 5],
       [9, 7]])

In [8]:
# different shape -----> LIST

np.array([[1,3],[2,5],[9,7,6]])

C:\Users\Utkarsh\AppData\Local\Temp/ipykernel_9856/3179349153.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[2,5],[9,7,6]])


array([list([1, 3]), list([2, 5]), list([9, 7, 6])], dtype=object)

In [9]:
np.array([[[1,3],[3,4]],[[1,3],[3,4]]])

array([[[1, 3],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

In [11]:
#3-d data

np.array([1,2,3], ndmin = 3)

array([[[1, 2, 3]]])

In [12]:
np.array([1,2,3], ndmin = 7)

array([[[[[[[1, 2, 3]]]]]]])

In [13]:
# dtype typecasting

np.array([1,2,3], ndmin = 3, dtype = complex)

array([[[1.+0.j, 2.+0.j, 3.+0.j]]])

In [14]:
# tuple bhi array ban sakta hai

l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [15]:
t = tuple(l)
t

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

In [16]:
np.array(t)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
# we can define dtype of individual dataset differently

In [18]:
arr = np.array([(23,56), (345, 6456)], dtype = [("a", "<i2"), ("b", "<i8")] )

arr

array([( 23,   56), (345, 6456)], dtype=[('a', '<i2'), ('b', '<i8')])

In [19]:
arr[0]

(23, 56)

In [20]:
arr[0][1]

56

In [21]:
type(arr[0][0])

numpy.int16

In [23]:
type(arr[0][1])

numpy.int64

In [28]:
arr = np.array([(23,56), (345, 6456)], dtype = [("a", "<i4"), ("b", "<i1")] )

arr

array([( 23, 56), (345, 56)], dtype=[('a', '<i4'), ('b', 'i1')])

In [29]:
type(arr[0][0])

numpy.int32

In [30]:
type(arr[0][1])

numpy.int8

In [31]:
# different types of array

# matrices are subsets of an array

In [32]:
l = [3,4,5,76,7]

In [33]:
np.array(l)

array([ 3,  4,  5, 76,  7])

In [34]:
np.asarray(l)

array([ 3,  4,  5, 76,  7])

In [35]:
np.asanyarray(l)

array([ 3,  4,  5, 76,  7])

In [38]:
mat = np.mat(l)

mat

matrix([[ 3,  4,  5, 76,  7]])

In [37]:
np.asanyarray(mat)

matrix([[ 3,  4,  5, 76,  7]])

In [1]:
# deepcopy vs shallow copy

In [2]:
import numpy as np
arr = np.array([[1,3], [3,4]])
arr

array([[1, 3],
       [3, 4]])

In [3]:
# shallowcopy

a = arr
a

array([[1, 3],
       [3, 4]])

In [4]:
arr[0][1] = 5
arr

array([[1, 5],
       [3, 4]])

In [5]:
a

array([[1, 5],
       [3, 4]])

In [6]:
# new array for deep copy

arr = np.array([[1,3], [3,4]])
arr

array([[1, 3],
       [3, 4]])

In [7]:
# deep copy
b = np.copy(arr)
b

array([[1, 3],
       [3, 4]])

In [8]:
arr[0][1] = 5
arr

array([[1, 5],
       [3, 4]])

In [9]:
# no change in b
b

array([[1, 3],
       [3, 4]])

In [10]:
# indexing in array start is inclusive and end is exclusive

In [11]:
arr[-1]

array([3, 4])

In [12]:
for i in arr:
    print(i)

[1 5]
[3 4]


In [13]:
for i in np.nditer(arr):
    print(i)

1
5
3
4


In [14]:
# from function

In [16]:
np.fromfunction(lambda i,j : i*j, (5,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.],
       [0., 3., 6.],
       [0., 4., 8.]])

In [18]:
np.fromfunction(lambda i,j : i==j, (5,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False]])

In [19]:
# fromiter function

In [21]:
gen = (i*i for i in range(1,9))
gen

<generator object <genexpr> at 0x000001F297ED95F0>

In [22]:
np.fromiter(gen, dtype = int)

array([       1,        4,       27,      256,     3125,    46656,
         823543, 16777216])

In [23]:
np.fromiter(range(6), dtype = int)

array([0, 1, 2, 3, 4, 5])

In [24]:
# np.fromstring

In [25]:
np.fromstring("1287723 23782349 32847394234 234283223 4234", sep= " ", dtype = int)

array([   1287723,   23782349, 2147483647,  234283223,       4234])

In [26]:
arr

array([[1, 5],
       [3, 4]])

In [27]:
arr.ndim

2

In [28]:
arr.size

4

In [29]:
arr.shape

(2, 2)

In [30]:
arr.item

<function ndarray.item>

In [32]:
arr.item(1)

5

In [33]:
arr

array([[1, 5],
       [3, 4]])

In [34]:
arr.item(3)

4

In [35]:
arr.item(4)

IndexError: index 4 is out of bounds for size 4

In [37]:
arr

array([[1, 3],
       [3, 4]])

In [40]:
arr.itemsize

4

In [41]:
arr2 = np.array([[[1,2,3,4],[4,5,6,7]],[[8,9,10,11],[12,13,14,15]]])
arr2

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [42]:
arr2.shape

(2, 2, 4)

In [44]:
range(123,22344, .3)

TypeError: 'float' object cannot be interpreted as an integer

In [43]:
np.arange(6.6, 9, .3)

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [45]:
np.linspace(2,89)

array([ 2.        ,  3.7755102 ,  5.55102041,  7.32653061,  9.10204082,
       10.87755102, 12.65306122, 14.42857143, 16.20408163, 17.97959184,
       19.75510204, 21.53061224, 23.30612245, 25.08163265, 26.85714286,
       28.63265306, 30.40816327, 32.18367347, 33.95918367, 35.73469388,
       37.51020408, 39.28571429, 41.06122449, 42.83673469, 44.6122449 ,
       46.3877551 , 48.16326531, 49.93877551, 51.71428571, 53.48979592,
       55.26530612, 57.04081633, 58.81632653, 60.59183673, 62.36734694,
       64.14285714, 65.91836735, 67.69387755, 69.46938776, 71.24489796,
       73.02040816, 74.79591837, 76.57142857, 78.34693878, 80.12244898,
       81.89795918, 83.67346939, 85.44897959, 87.2244898 , 89.        ])

In [48]:
np.linspace(2,90, 45)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24., 26.,
       28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48., 50., 52.,
       54., 56., 58., 60., 62., 64., 66., 68., 70., 72., 74., 76., 78.,
       80., 82., 84., 86., 88., 90.])

In [49]:
np.linspace(2,90, 12)

array([ 2., 10., 18., 26., 34., 42., 50., 58., 66., 74., 82., 90.])

In [50]:
np.linspace(2,90, 9)

array([ 2., 13., 24., 35., 46., 57., 68., 79., 90.])

In [51]:
np.linspace(2,90, 9, dtype = int)

array([ 2, 13, 24, 35, 46, 57, 68, 79, 90])

In [52]:
np.linspace([2],[90], 9, dtype = int)

array([[ 2],
       [13],
       [24],
       [35],
       [46],
       [57],
       [68],
       [79],
       [90]])

In [53]:
np.linspace([2],[90], 9, dtype = int, axis=1)

array([[ 2, 13, 24, 35, 46, 57, 68, 79, 90]])

In [56]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [57]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [59]:
np.zeros((5,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [60]:
np.eye((7,3))

TypeError: 'tuple' object cannot be interpreted as an integer

In [61]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [62]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
np.eye(7,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
np.identity(5,3 )

TypeError: Cannot interpret '3' as a data type

In [66]:
np.ones(3,4)

TypeError: Cannot interpret '4' as a data type

In [67]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [69]:
np.empty(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [72]:
np.empty((2,3,4), dtype = int)

array([[[         0, 1072693248,          0, 1072693248],
        [         0, 1072693248,          0, 1072693248],
        [         0, 1072693248,          0, 1072693248]],

       [[         0, 1072693248,          0, 1072693248],
        [         0, 1072693248,          0, 1072693248],
        [         0, 1072693248,          0, 1072693248]]])

In [76]:
np.logspace(2,3, endpoint=False, dtype=int)

array([100, 104, 109, 114, 120, 125, 131, 138, 144, 151, 158, 165, 173,
       181, 190, 199, 208, 218, 229, 239, 251, 263, 275, 288, 301, 316,
       331, 346, 363, 380, 398, 416, 436, 457, 478, 501, 524, 549, 575,
       602, 630, 660, 691, 724, 758, 794, 831, 870, 912, 954])

In [77]:
np.transpose(arr)

array([[1, 3],
       [3, 4]])

In [78]:
arr

array([[1, 3],
       [3, 4]])

In [79]:
arr == np.transpose(arr)

array([[ True,  True],
       [ True,  True]])

In [80]:
arr == arr.T

array([[ True,  True],
       [ True,  True]])

In [81]:
arr

array([[1, 3],
       [3, 4]])

In [82]:
arr.size

4

In [83]:
arr.reshape(1,1,4)

array([[[1, 3, 3, 4]]])

In [84]:
arr.reshape(1,2,2)

array([[[1, 3],
        [3, 4]]])

In [85]:
arr.reshape(2,1,2)

array([[[1, 3]],

       [[3, 4]]])

In [86]:
arr.reshape(1,4,1)

array([[[1],
        [3],
        [3],
        [4]]])

In [87]:
arr.reshape(2,2,1)

array([[[1],
        [3]],

       [[3],
        [4]]])

In [88]:
arr.reshape(2,2,2)

ValueError: cannot reshape array of size 4 into shape (2,2,2)

In [89]:
np.max(arr)

4

In [90]:
arr.max()

4

In [95]:
arr = np.random.randint(10, 51, (4,7))

In [96]:
arr

array([[24, 14, 21, 48, 39, 28, 29],
       [41, 49, 49, 12, 19, 15, 38],
       [15, 16, 20, 35, 34, 35, 31],
       [10, 45, 24, 23, 37, 32, 40]])

In [97]:
arr[2:,4: ]

array([[34, 35, 31],
       [37, 32, 40]])

In [99]:
arr[0:,[1,3,6]]

array([[14, 48, 29],
       [49, 12, 38],
       [16, 35, 31],
       [45, 23, 40]])

In [100]:
arr > 43

array([[False, False, False,  True, False, False, False],
       [False,  True,  True, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False]])

In [101]:
arr[arr>43]

array([48, 49, 49, 45])

In [102]:
np.sin(arr)

array([[-0.90557836,  0.99060736,  0.83665564, -0.76825466,  0.96379539,
         0.27090579, -0.66363388],
       [-0.15862267, -0.95375265, -0.95375265, -0.53657292,  0.14987721,
         0.65028784,  0.29636858],
       [ 0.65028784, -0.28790332,  0.91294525, -0.42818267,  0.52908269,
        -0.42818267, -0.40403765],
       [-0.54402111,  0.85090352, -0.90557836, -0.8462204 , -0.64353813,
         0.55142668,  0.74511316]])

In [103]:
arr2

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [104]:
arr*arr

array([[ 576,  196,  441, 2304, 1521,  784,  841],
       [1681, 2401, 2401,  144,  361,  225, 1444],
       [ 225,  256,  400, 1225, 1156, 1225,  961],
       [ 100, 2025,  576,  529, 1369, 1024, 1600]])

In [105]:
arr

array([[24, 14, 21, 48, 39, 28, 29],
       [41, 49, 49, 12, 19, 15, 38],
       [15, 16, 20, 35, 34, 35, 31],
       [10, 45, 24, 23, 37, 32, 40]])

In [106]:
arr*10

array([[240, 140, 210, 480, 390, 280, 290],
       [410, 490, 490, 120, 190, 150, 380],
       [150, 160, 200, 350, 340, 350, 310],
       [100, 450, 240, 230, 370, 320, 400]])

In [107]:
arr+10

array([[34, 24, 31, 58, 49, 38, 39],
       [51, 59, 59, 22, 29, 25, 48],
       [25, 26, 30, 45, 44, 45, 41],
       [20, 55, 34, 33, 47, 42, 50]])

In [108]:
arr

array([[24, 14, 21, 48, 39, 28, 29],
       [41, 49, 49, 12, 19, 15, 38],
       [15, 16, 20, 35, 34, 35, 31],
       [10, 45, 24, 23, 37, 32, 40]])

In [109]:
arr1 = np.random.randint(1,9, (3,3))

In [110]:
arr2 = np.random.randint(1,9, (2,3))

In [111]:
arr1

array([[6, 8, 3],
       [4, 7, 5],
       [3, 8, 3]])

In [112]:
arr2

array([[2, 2, 2],
       [5, 3, 2]])

In [113]:
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [114]:
arr1*arr2

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [115]:
arr2*arr1

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [116]:
arr1@arr2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [117]:
arr2@arr1

array([[26, 46, 22],
       [48, 77, 36]])

In [118]:
# broadcasting

In [119]:
a = np.array([65,5,54])

In [120]:
a

array([65,  5, 54])

In [121]:
arr1

array([[6, 8, 3],
       [4, 7, 5],
       [3, 8, 3]])

In [122]:
arr1+a

array([[71, 13, 57],
       [69, 12, 59],
       [68, 13, 57]])

In [123]:
a+arr1

array([[71, 13, 57],
       [69, 12, 59],
       [68, 13, 57]])

In [124]:
arr2

array([[2, 2, 2],
       [5, 3, 2]])

In [125]:
a

array([65,  5, 54])

In [126]:
arr2+a

array([[67,  7, 56],
       [70,  8, 56]])

In [127]:
arr2 = arr2.T

In [128]:
arr2

array([[2, 5],
       [2, 3],
       [2, 2]])

In [129]:
a

array([65,  5, 54])

In [130]:
arr2 + a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [131]:
np.square(arr1)

array([[36, 64,  9],
       [16, 49, 25],
       [ 9, 64,  9]], dtype=int32)